name: '0.0$(Rev:.r)'
variables:
    organization: 
    AzureDevOpsProjectID: 
    secureFileName: 
    secureFileFolder:
trigger:
- none
pool:
  vmImage: macos-13
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |    
      $header = @{ Authorization = "Bearer $env:ACCESSTOKEN" }
      $infile = "$(secureFileFolder)/$(secureFileName)"
      $organization = (Split-Path $(System.CollectionUri) -leaf)
      $uri = "https://dev.azure.com/$organization/$(AzureDevOpsProjectID)/_apis/distributedtask/securefiles?api-version=5.0-preview.1&name=$(secureFileName)"
      Invoke-RestMethod -Uri $uri -Method Post -ContentType "application/octet-stream" -Headers $header -InFile "$infile
  enabled: true


